name: Backup to private repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Setup SSH
        env:
          DEPLOY_KEY: ${{ secrets.BACKUP_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Fetch additional resources and clean up
        env:
          BACKUP_REPO : ${{ secrets.BACKUP_REPO }}
        run: |
          mkdir -p temp-backup
          git clone --branch res --depth 1 git@github.com:$BACKUP_REPO.git temp-backup
          cp -rfv temp-backup/* ./
          rm -rf temp-backup
          rm -rf .github

      - name: Squash contents
        run: |
          git add -A
          git reset $(git commit-tree HEAD^{tree} -m "Sync commit(s) from diff-teatime/main")
          git add -A
          git commit --amend -m "Sync commit(s) from diff-teatime/main"

      - name: Force push to backup
        env:
          BACKUP_REPO : ${{ secrets.BACKUP_REPO }}
        run: |
          git push -f git@github.com:$BACKUP_REPO.git main