name: Backup to private repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch additional resources and clean up
        env:
          PAT: ${{ secrets.BACKUP_REPO_TOKEN }}
          BACKUP_REPO : ${{ secrets.BACKUP_REPO }}
        run: |
          mkdir -p temp-backup
          git clone --branch res --depth 1 https://$PAT@github.com/$BACKUP_REPO.git temp-backup
          cp -rfv temp-backup/* ./
          rm -rf temp-backup
          rm -rf .github

      - name: Squash contents
        run: |
          git add -A
          git reset $(git commit-tree HEAD^{tree} -m "Sync commit(s) from diff-teatime/main")
          git commit --amend -m "Sync commit(s) from diff-teatime/main"

      - name: Force push to backup
        env:
          PAT: ${{ secrets.BACKUP_REPO_TOKEN }}
          BACKUP_REPO : ${{ secrets.BACKUP_REPO }}
        run: |
          git remote add backup https://$PAT@github.com/$BACKUP_REPO.git
          git push -f backup main